# GitHub action to build repos that are dependent on this library
name: Build Dependent Repos

on: 
  release:
    types: [published,edited]
  workflow_dispatch:
    inputs:
      message:
        description: Message to display in job summary
        required: false
        type: string

jobs:
  build-dependent-repos:
    strategy:
      matrix:
        include:
          - name: Trigger build on Weather_Sensors_SWI2C
            repo: Weather_Sensors_SWI2C
          - name: Trigger build on MSP430TempSensorWithDisplay
            repo: MSP430TempSensorWithDisplay
          - name: Trigger build on Sensor-Repeater
            repo: Sensor-Repeater
          - name: Trigger build on BQ27441_SWI2C
            repo: BQ27441_SWI2C
          - name: Trigger build on EEPROM_24C08_SWI2C
            repo: EEPROM_24C08_SWI2C
          - name: Trigger build on Outdoor-Weather-Sensor
            repo: Outdoor-Weather-Sensor
          - name: Trigger build on MSP430TempSensorLCD
            repo: MSP430TempSensorLCD

    name: call-compile-sketches-workflow
    uses: Andy4495/.github/.github/workflows/build-dependent-repos.yml@main
    with:
      message: ${{ inputs.message }}
      repo-name: ${{ matrix.repo }}
    secrets: inherit

            